apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus--crud
  namespace: quarkus--crud
  labels:
    app: quarkus--crud
spec:
  selector:
    matchLabels:
      app: quarkus--crud
  template:
    metadata:
      labels:
        app: quarkus--crud
    spec:
      containers:
        - name: quarkus--crud
          image: localhost:32000/quarkus-crud:latest
          readinessProbe:
            httpGet:
              path: /q/health/live
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /q/health/ready
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 10

          resources:
            requests:
              memory: "400Mi"
              cpu: "400m"
            limits:
              memory: "400Mi"
              cpu: "400m"

          envFrom:
            - configMapRef:
                name: quarkus--crud-cm
          ports:
            - containerPort: 5000

