apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quarkus--crud-hpa
  namespace: quarkus--crud
  labels:
    app: quarkus--crud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quarkus--crud
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50