apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: quarkus--crud-kustomization
  namespace: quarkus--crud
resources:
  - service.yaml
  - deployment.yaml
  - horizontalPodScaling.yaml
  - secrets.yaml
  - namespace.yaml
  - configMap.yaml