quarkus:

  datasource:
    db-kind: mysql
    username: root
    password: admin
    jdbc:
      url: "jdbc:mysql://localhost:3303/db_quarkus?useSSL=false"

  hibernate-orm:
    database:
      generation: update

https:
  protocols: "TLSv1 TLSv1.1 TLSv1.2 TLSv1.3"