quarkus:
  http:
    port: 5000

  log:
    level: INFO
    min-level: TRACE

    category:
      "io.quarkus.category":
        level: INFO

      "org.jboss.resteasy.reactive.server.handlers.ParameterHandler":
        level: DEBUG

      "org.apache.http":
        level: TRACE

      "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext":
        level: TRACE