quarkus:
  http:
    port: 5000

  datasource:
    db-kind: mysql
    username: wb-quarkus-usuarios
    password: quarkusdb
    jdbc:
      url: ${DATABASE_HOST}

  hibernate-orm:
    database:
      generation: update