quarkus:
  http:
    port: 5000
    access-log:
      enabled: true



  log:
    level: INFO
    min-level: TRACE

    category:
      "io.quarkus.category":
        level: TRACE

      "org.jboss.resteasy.reactive.server.handlers.ParameterHandler":
        level: DEBUG

      "org.apache.http":
        level: TRACE

      "org.jboss.resteasy.reactive":
        level: TRACE