quarkus:

  datasource:
    db-kind: mysql
    credentials-provider: custom
    credentials-provider-name: aws-secret-manager #Caso possui varios provider diferentes para bases diferentes, utilize essa propriedade para especificar um provider para cada datasource
    jdbc:
      url: "jdbc:mysql://127.0.0.1:3303/db_quarkus"
  hibernate-orm:
    database:
      generation: update

  secretsmanager:
#    endpoint-override: http://localhost:4566 Apenas para caso utilizar LocalStack
    aws:
      region: us-east-1

aws:
  secret-name: mysql/db_quarkus
