quarkus:
  http:
    port: 5000

  aws:
    secretName: mysql/db_quarkus

  datasource:
    db-kind: mysql
    username: wb-quarkus-usuarios
    password: quarkusdb
    jdbc:
      url: "jdbc:mysql://127.0.0.1:3303/db_quarkus"

  hibernate-orm:
    database:
      generation: update