quarkus:
  http:
    port: 5000

  datasource:
    db-kind: mssql
    username: sa
    password: Pass@word
    jdbc:
      url: "jdbc:sqlserver://127.0.0.1:5434;DatabaseName=db_quarkus"

  hibernate-orm:
    database:
      generation: update