quarkus:
  http:
    port: 5000

  datasource:
    db-kind: mysql
    username: wb-quarkus-usuarios
    password: password
    jdbc:
      url: "jdbc:mysql://127.0.0.1:3306"

  hibernate-orm:
    database:
      generation: update