quarkus:

  datasource:
    db-kind: mysql
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}
    jdbc:
      url: ${DATABASE_HOST}

  hibernate-orm:
    database:
      generation: none