quarkus:
  http:
    port: 5000

  datasource:
    db-kind: mysql
    credentials-provider: custom
    jdbc:
      url: "jdbc:mysql://127.0.0.1:3303/db_quarkus2"
  hibernate-orm:
    database:
      generation: update

aws:
  secret-name: mysql/db_quarkus
  url: "http://localhost:4566"
  region: "us-east-1"