quarkus:
  http:
    port: 5000

    cors:
      ~: true
      origins: 'http://localhost:5173'
  datasource:
    db-kind: mysql
    username: wb-quarkus-usuarios
    password: quarkusdb
    jdbc:
      url: "jdbc:mysql://127.0.0.1:3303/db_quarkus"

  hibernate-orm:
    database:
      generation: update